services:
  backend:
    container_name: nodejs-backend
    image: dockerlunchopsacr.azurecr.io/nodejs-backend:latest
    command: npm run start-watch
    environment:
      - DATABASE_DB=example
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
      - NODE_ENV=development
    ports:
      - 80:80
      - 9229:9229
      - 9230:9230
    secrets:
      - db-password
    depends_on:
      - db
  db:
    container_name: maria-db
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    secrets:
      - db-password
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  frontend:
    container_name: react-frontend
    image: dockerlunchopsacr.azurecr.io/react-frontend:latest
    ports:
      - 3000:3000
    depends_on:
      - backend
secrets:
  db-password:
    file: db/password.txt
